server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: json-service
          uri: lb://json-service
          predicates:
            - Path=/api/json/**
          filters:
            - StripPrefix=2

        - id: xml-service
          uri: lb://xml-service
          predicates:
            - Path=/api/xml/**
          filters:
            - StripPrefix=2

        - id: yaml-service
          uri: lb://yaml-service
          predicates:
            - Path=/api/yaml/**
          filters:
            - StripPrefix=2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
