server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: json-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/json/**
          filters:
            - StripPrefix=2

        - id: xml-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/xml/**
          filters:
            - StripPrefix=2

        - id: yaml-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/yaml/**
          filters:
            - StripPrefix=2

